language: java
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: FgtZ4i9EyUm2zoeqA90SjlR4WKsAImo1zVWVavYA2SY4dIRGRYeCSN/E6ANtvf9GZl3Op0Y91i1Q5wVE93AQAQbYCffyxdt92O94cwIjkNGv7wF036S3kxHqilqY15fBo8xxx3oprBYqOptmAaKlE/s0LGL+5Kk12DdOIUto+IdC+RdeIhNWrZCOiFSGzPPmI2HBWPLtzKvl9mt7zGZ8JVn8W37mQkk6z55ya8TTNYpv3ROHNm46Z8NsCigy2jGZqWmjJhuvOEUsN42U1QlWnidDus5U09xlHHnGUkFHBm7N4cVwVITzWQf9oT12dWi56r5KEOEIlHdgCUPT8kwJoMJ+0cWCiyGv16LBxRdR4botoVMBmJ7nVG0b1+Votzd/HYHcF5GImnl7xhnVFItOcIy236NiG3CfybxiGQLzTGM0LnyeJYkdTFUyw1muR4+saZ5lz0ikyJiHOdR0MG3ADRT1VtK4g+masc7zYObGzMHqq6f5A7Zr029KyY8hhX/rDtfdBHC8uXf4O8ak5Keqt4BQkj2ElnWPKh/1oLPAhitrYp1wYQlFNMGNJrVQGztXueiTenMVZrjkH3lxwrNsbarz3Jrkg4K4DCj2/eKT+5u5dup4J34+NgCoZza1d94acdboAdf0NeeCC7R7QNcXpzpSg2j6nhLxWsWpcdfdn6s=
  file: target/gnuob-login.jar
  on:
    tags: true