language: java
jdk: oraclejdk8
deploy:
  provider: releases
  api_key:
    secure: Yh5Wky6xPOvx8QOCXslHRRRrO+y+ACITK8Rf6EWIVDLSSc+wMRNYyIb7R2d3SjrYlS/Tyh9mLUij8DqmnyOZZKfmJ1GmVSR+JaxHKb103Jr4Cef5nk/L4nAnmejyklJHWvw0eYUlezAUxq0VbXQNwagsN0/zslbpOvRJUNKo7RdDUGNw/x4QjVv73odZ2yWMLOXnVzu4Y2XheNbzWnaochcTNBNdzweFf6GcdsBr7zulzqcrwUJP/6cIYvDBbVfpYKKCnLfvXmZnauCIyn75wDsHBsKgACVQOTqoYSgJF8nVAWGCzEPVNqT60/3sHbV1930Gstyze1sd6Dhiyflk2XVkpdqMoAU5dfEnFrgIdu7Kg1vrjBrkqGsUnx8b6lhpBWNY/m0grnoJ6qbsBLsZAnUUP38tE9kKlYu6q6msGSCr1pve5RoPF5xNgLM/I6rK33P158jSd2QeWevwtjPsDyyyOXguPKqP6Mge/su5H5XXcCV7aYgG+sNXUuiXLqyBm5gLKBnG6h2HuWKbqwQjQL+IzD3DcJ6MeOW/1P+Iz64ooGUk6/UVpRUyoG3AmaarKnlxuZYS0Lxm/agugywdlQ3MiTrVHdjRGyx5UTu13My4jNud28A570Ty+94z4Wcr9uE/Jiuj27mbAvXWtEQSwkdF8B+jNUXvBXZDf+wVXLs=
  file: target/gnuob-login.jar
  skip_cleanup: true
  on:
    tags: true
